### ISSUE TITLE
Error on loading package

### ISSUE THREAD

**Issue by dgermanwildlife** [michaeldorman/geobgu#1]
I have been using this package on a desktop, but am switching to a laptop and thus reloading the package.  On trying to load I get the error shown below.  I see that you recently deleted the detrend and flowlength from the code and am wondering if that is why I'm not able to load the package?

** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'geobgu' in namespaceExport(ns, exports):
 undefined exports: detrend, flowlength
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'geobgu' in namespaceExport(ns, exports):
 undefined exports: detrend, flowlength
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Program Files/R/library/geobgu'
Error: Failed to install 'geobgu' from GitHub:
  (converted from warning) installation of package ‘C:/Users/dgerman/AppData/Local/Temp/RtmpI14m3z/file8e648325f3bae/geobgu_0.2.3.tar.gz’ had non-zero exit status

**Comment by michaeldorman** [comment]
Sorry, like you say I removed functions `detrend` and `flowlength` but forgot to update package documentation. Now it should work, please let me know if there is any other issue. 

P.S. (improved versions of) these two functions were moved to a separate package named `starsExtra` (https://github.com/michaeldorman/starsExtra)
